In [9]:
import numpy as np

arr = np.array([1.0, 2.0, 3.0], int)
arr

array([1, 2, 3])

In [10]:
arr1 = np.array([1.0, "2", 3], int)
arr1

array([1, 2, 3])

In [11]:
arr2 = np.array([1.0, "2", 3], int)
arr2

array([1, 2, 3])

In [12]:
arr2

array([1, 2, 3])

In [13]:
type(arr2)

numpy.ndarray

In [25]:
arr3 = arr2.astype(np.float32)
arr3

array([1., 2., 3.], dtype=float32)

In [28]:
arr3=arr2.astype(np.float64)
arr3

array([1., 2., 3.])