In [5]:
import numpy as np
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
arr=np.ones(10)

In [7]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
aa=np.full(3,3)
aa

array([3, 3, 3])

In [11]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
a=np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])