In [2]:
import numpy as np

num = [1, 2, 3]
arr = np.array(num)
print(arr)

[1 2 3]


In [2]:
type(num)

list

In [3]:
type(arr)

numpy.ndarray

In [4]:
for i in num:
    print(i)

1
2
3


In [5]:
for i in arr:
    print(i)

1
2
3


In [3]:
num1 = [[1, 2, 3], [4, 5, 6]]
arr1 = np.array(num1)
for i in range(2):
    for j in range(3):
        print(num1[i][j], end=" ")
    print()

1 2 3 
4 5 6 


In [4]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
num1

[[1, 2, 3], [4, 5, 6]]

In [7]:
for i in range(2):
    for j in range(3):
        print(num1[i][j], end=" ")
    print()

1 2 3 
4 5 6 


In [8]:
arr3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
type(arr3)

numpy.ndarray

In [17]:
arr

array([1, 2, 3])

In [20]:
arr.ndim

1

In [22]:
arr1.ndim

2

In [23]:
arr.shape

(3,)

In [24]:
arr1.shape

(2, 3)

In [25]:
arr.size

3

In [11]:
arr1.size

6

In [12]:
arr.dtype

dtype('int64')

In [13]:
arr1.dtype

dtype('int64')

In [14]:
arr.dtype

dtype('int64')

In [20]:
arr.itemsize

8

In [21]:
arr1.itemsize

8

In [22]:
arr.nbytes

24

In [23]:
arr1.nbytes

48