In [1]:
import numpy as np

In [25]:
# 예제
# arr=np.array([3,5,4,1,7])
# 1. arr 배열에 원소 8을 추가
# 2. arr 1번 인덱스 위치에 원소 10 삽입
# 3. arr 5번 인덱스 위치에 원소 3 삽입
# 4. arr 배열에 4번 인덱스 삭제
# 5. arr 배열에 중복된 원소를 제거


arr = np.array([3, 5, 4, 1, 7])
# 1. arr 배열에 원소 8을 추가
arr1 = np.append(arr, 8)
arr1

array([3, 5, 4, 1, 7, 8])

In [26]:
# 2. arr 1번 인덱스 위치에 원소 10 삽입
arr2 = np.insert(arr1, 1, 10)
arr2

array([ 3, 10,  5,  4,  1,  7,  8])

In [30]:
# 3. arr 5번 인덱스 위치에 원소 3 삽입
arr3 = np.insert(arr2, 5, 3)
arr3

array([ 3, 10,  5,  4,  1,  3,  7,  8])

In [31]:
# 4. arr 배열에 4번 인덱스 삭제
arr4 = np.delete(arr3, 4)
arr4

array([ 3, 10,  5,  4,  3,  7,  8])

In [32]:
# 5. arr 배열에 중복된 원소를 제거
arr5 = np.unique(arr4)
arr5

array([ 3,  4,  5,  7,  8, 10])