In [1]:
import numpy as np
arr=np.arange(1,10,1)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [2]:
arr1=np.reshape(arr,(3,3))
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
arr3=np.arange(5,13)
print(arr3)


[ 5  6  7  8  9 10 11 12]


In [4]:
arr4=arr3.reshape(2,4)
print(arr4)

[[ 5  6  7  8]
 [ 9 10 11 12]]
