In [1]:
import numpy as np

arr = np.array([5, 4, 2, 9, 3])

np.sum(arr)

np.float64(2.4166091947189146)

In [2]:
np.mean(arr)

np.float64(4.6)

In [3]:
np.max(arr)

np.int64(9)

In [4]:
np.min(arr)

np.int64(2)

In [5]:
np.var(arr)

np.float64(5.84)

In [6]:
np.std(arr)

np.float64(2.4166091947189146)

In [8]:
np.sign(arr)

array([1, 1, 1, 1, 1])

In [10]:
np.cumsum(arr)

array([ 5,  9, 11, 20, 23])

In [11]:
np.trunc(arr)

array([5., 4., 2., 9., 3.])

In [13]:
#============
maxIndex=np.argmax(arr)
maxIndex

np.int64(3)

In [15]:
minIndex=np.argmin(arr)
minIndex

np.int64(2)

In [27]:
# page 192 4번 내림차순
arr = np.array([80, 90, 80, 100, 60])
arrRsort = np.flip(np.sort(arr))
# == arrRsort = np.sort(arr)[::-1]
for i in arrRsort:
    print(i)

100
90
80
80
60


In [31]:
# page 192 5번 sales 배열에서 2주동안의 커피 판매량 항목
# HINT
# cumsum()

# 풀이1
sales = np.array([5, 7, 3, 6, 2, 4, 8, 7, 5, 4, 3, 12, 4, 2])
sales_zip = zip(sales, np.cumsum(sales))
day = 0
for perday, cumulative_sales in sales_zip:
    day += 1
    print(f"{day:>2}일 판매량: {perday:>2} \t 누적 판매 : {cumulative_sales:>2}")

 1일 판매량:  5 	 누적 판매 :  5
 2일 판매량:  7 	 누적 판매 : 12
 3일 판매량:  3 	 누적 판매 : 15
 4일 판매량:  6 	 누적 판매 : 21
 5일 판매량:  2 	 누적 판매 : 23
 6일 판매량:  4 	 누적 판매 : 27
 7일 판매량:  8 	 누적 판매 : 35
 8일 판매량:  7 	 누적 판매 : 42
 9일 판매량:  5 	 누적 판매 : 47
10일 판매량:  4 	 누적 판매 : 51
11일 판매량:  3 	 누적 판매 : 54
12일 판매량: 12 	 누적 판매 : 66
13일 판매량:  4 	 누적 판매 : 70
14일 판매량:  2 	 누적 판매 : 72


In [34]:
# 풀이2
grand_sales = np.cumsum(sales)
for i in range(len(sales)):
    print(f"{i + 1:>2}일 판매량: {sales[i]:>2} \t 누적 판매 : {grand_sales[i]:>2}")

 1일 판매량:  5 	 누적 판매 :  5
 2일 판매량:  7 	 누적 판매 : 12
 3일 판매량:  3 	 누적 판매 : 15
 4일 판매량:  6 	 누적 판매 : 21
 5일 판매량:  2 	 누적 판매 : 23
 6일 판매량:  4 	 누적 판매 : 27
 7일 판매량:  8 	 누적 판매 : 35
 8일 판매량:  7 	 누적 판매 : 42
 9일 판매량:  5 	 누적 판매 : 47
10일 판매량:  4 	 누적 판매 : 51
11일 판매량:  3 	 누적 판매 : 54
12일 판매량: 12 	 누적 판매 : 66
13일 판매량:  4 	 누적 판매 : 70
14일 판매량:  2 	 누적 판매 : 72
