In [1]:
import numpy as np

num1 = np.array([1, 2, 3])
num2 = np.array([4, 5, 6])
print(np.add(num1, num2))

[5 7 9]


In [2]:
print(np.subtract(num2, num1))
print(np.multiply(num1, num2))

[3 3 3]
[ 4 10 18]


In [3]:
print(np.divide(num1, num2))

[0.25 0.4  0.5 ]


In [22]:
print(np.dot(num1, num2))

32


In [11]:
arr = [4, 1, 2, 7, 9, 8, 5]
# arr 전체 출력
print(arr)
print(arr[0:])
print(arr[:])
# arr 2,7,9 출력
print(arr[2:5:1])

[4, 1, 2, 7, 9, 8, 5]
[4, 1, 2, 7, 9, 8, 5]
[4, 1, 2, 7, 9, 8, 5]
[2, 7, 9]


In [13]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
arr2[:2, :2]  # == arr2[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [18]:
arr2[:2, 1:]  # == arr2[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [20]:
arr2[1:]  # == arr2[1:3, 0:3] == arr2[1:, :3]

array([[4, 5, 6],
       [7, 8, 9]])